version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ParkingSystem/ParkingSystem"
    schedule:
      interval: "daily"  # Use daily instead of "live" for NuGet
    open-pull-requests-limit: 5
