name: Build and Push API

on:
  # TODO: temporary while testing, will be changed to run on pull_request to main
  workflow_dispatch:
  push:
    branches:
      - dev-dynamic-analysis-artifact-scanning
    paths:
      - ParkingSystem/**
      - .github/workflows/build_api.yaml

env:
  VERSION: 0.0.1
  # FIXME: token is in clear text since I don't have admin access to our github repo
  DOCKER_USER: lew6s
  DOCKER_PASS: dckr_pat_sQeO65WFLgDPo0LYNtxILaLdGiI

jobs:
  build-api:
    runs-on: ubuntu-22.04  
    permissions:
      security-events: write
      pull-requests: read
      contents: write
      id-token: write
      statuses: write
      actions: read
      pages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ParkingSystem
          push: true
          load: true
          tags: lew6s/parking-system:0.0.1

      - name: Scan built Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'lew6s/parking-system:${{ env.VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Fail build on High/Criticial Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          format: json
          image-ref: 'lew6s/parking-system:${{ env.VERSION }}'
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 1
          cache: 'false'

