name: Generate SBOM

on:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        working-directory: ParkingSystem/ParkingSystem
        run: dotnet restore

      - name: Install CycloneDX tool
        run: dotnet tool install --global CycloneDX

      - name: Generate SBOM
        working-directory: ParkingSystem/ParkingSystem
        run: dotnet CycloneDX ParkingSystem.csproj --output ./sbom --json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: ParkingSystem/ParkingSystem/sbom
