name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Begin SonarCloud analysis
        run: dotnet-sonarscanner begin /k:"JoanaGMoreira_desofs2025_wed_nap_1" /o:"joanagmoreira" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore dependencies
        run: dotnet restore ParkingSystem/ParkingSystem.sln

      - name: Build solution
        run: dotnet build ParkingSystem/ParkingSystem.sln --no-restore --no-incremental

      - name: End SonarCloud analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
